### ISSUE TITLE
Security risk: Amazon S3 secret key is in .travil.yml file

### ISSUE THREAD

**Issue by asgarli** [phillyrb/phillyrb.org#31]
I've noticed .travis.yml stores data to access S3 bucket for both beta and **main** website. This is a  security risk I believe (though I don't have a proof - haven't tried to hack the website), it should be fixed somehow.

**Comment by justincampbell** [comment]
Thanks @asgarli. This is intentional. The secret is encrypted by the travis cli command, and they have the decryption keys. See http://docs.travis-ci.com/user/encryption-keys/ for more information.
